# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # Optionally specify other tools, e.g., nodejs or rust
    # nodejs: "20"
    # rust: "1.70"
    # golang: "1.20"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: "dirhtml"  # You can use "html" if you prefer standard HTML output
  fail_on_warning: true  # Fail the build if warnings are encountered

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Declare the Python requirements required to build your documentation
# This ensures that Read the Docs installs your dependencies, including sphinx-reredirects
python:
  install:
    - requirements: docs/requirements.txt

# Optionally add environment variables or extra setup
# environment:
#   variables:
#     MY_VARIABLE: "value"
