# Read the Docs configuration file for Sphinx projects
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: en_us/contribute/source/conf.py  # Updated path to your conf.py
  builder: "html"  # Changed from dirhtml to html for standard output
  fail_on_warning: true

formats:
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt  # Ensure this path is correct

# Optional environment variables section
# environment:
#   variables:
#     MY_VARIABLE: "value"
